baseURL = "https://tehlastjuan.github.io/compendium/"
title = "Rollspellspoolen Compendium"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableGitInfo = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

# [caches]
#   [caches.images]
#     dir = ":cacheDir/images"

[outputs]
  section = ["HTML", "RSS", "print"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "Smart"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    noClasses = false
  [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  #privacy_policy = "https://policies.google.com/privacy"
  #version_menu = "Releases"
  #archived_version = false
  #version = "0.12.0"
  #url_latest_version = "https://example.com"
  #github_repo = "https://github.com/google/docsy"
  #github_project_repo = "https://github.com/google/docsy"
  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  offlineSearch = true
  offlineSearchSummaryLength = 20
  offlineSearchMaxResults = 10
  rss_sections = ['blog']
  #prism_syntax_highlighting = false
  #search = algolia

  [params.copyright]
    authors =  "Rollspelspoolen | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0)"
    from_year = 2017

  [params.taxonomy]
    # set taxonomyCloud = [] to hide taxonomy clouds
    taxonomyCloud = ["tags", "categories"]
    # If used, must have same length as taxonomyCloud
    taxonomyCloudTitle = ["Tag Cloud", "Categories"]
    # set taxonomyPageHeader = [] to hide taxonomies on the page headers
    taxonomyPageHeader = ["tags", "categories"]

  [params.ui]
    breadcrumb_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    showLightDarkModeMenu = true
    sidebar_cache_limit = 10
    sidebar_menu_compact = true
    sidebar_menu_foldable = true
    sidebar_search_disable = false

    [params.ui.readingtime]
      enable = false

  [params.plantuml]
    enable = true
    theme = "default"
    svg_image_url = "https://www.plantuml.com/plantuml/svg/"
    svg = false
  [params.print]
    disable_toc = false
  [params.markmap]
    enable = true
  [params.drawio]
    enable = true

# Docsy config

[outputFormats.PRINT]
  baseName = "index"
  isHTML = true
  mediaType = "text/html"
  path = "_print"
  permalinkable = false

[module]
  # replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "node_modules/bootstrap"
    target = "assets/vendor/bootstrap"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free"
    target = "assets/vendor/Font-Awesome"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

  # if using npm
  # [[module.mounts]]
  #   source = "../../node_modules/bootstrap"
  #   target = "assets/vendor/bootstrap"
  # [[module.mounts]]
  #   source = "../../node_modules/@fortawesome/fontawesome-free"
  #   target = "assets/vendor/Font-Awesome"
  # [[module.mounts]]
  #   source = "../../node_modules/@fortawesome/fontawesome-free/webfonts"
  #   target = "static/webfonts"

  # bug fix
  [[module.mounts]]
    source = "assets/_vendor/bootstrap/scss"
    target = "assets/vendor/bootstrap/scss/vendor"

  # imports
  [[module.imports]]
    path = "github.com/twbs/bootstrap"
    disable = false
  [[module.imports.mounts]]
    source = "scss"
    target = "assets/vendor/bootstrap/scss"
  [[module.imports.mounts]]
    source = "dist/js"
    target = "assets/vendor/bootstrap/dist/js"

  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = false
  [[module.imports.mounts]]
    source = "scss"
    target = "assets/vendor/Font-Awesome/scss"
  [[module.imports.mounts]]
    source = "webfonts"
    target = "static/webfonts"

