baseURL = "/"
title = ""
defaultContentLanguage = "en"

enableRobotsTXT = true
enableGitInfo = true
contentDir = "content/en"
#ignoreLogs = ['warning-frontmatter-params-overrides', 'warning-goldmark-raw-html']

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[module]
  replacements = "github.com/FortAwesome/Font-Awesome -> ., github.com/twbs/bootstrap -> ."
  [module.hugoVersion]
    extended = true
    min = "0.112.0"
  [[module.imports]]
    path = "docsy"
  [[module.mounts]]
    source = "content"
    target = "content"

[outputs]
  section = ["HTML", "RSS", "print"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "Smart"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    noClasses = false
  [markup.goldmark.parser.attribute]
    block = true
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  #privacy_policy = "https://policies.google.com/privacy"
  #version_menu = "Releases"
  #archived_version = false
  #version = "0.12.0"
  #url_latest_version = "https://example.com"
  #github_repo = "https://github.com/google/docsy"
  #github_project_repo = "https://github.com/google/docsy"
  #github_subdir = "userguide"
  #time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  offlineSearch = false
  #offlineSearchSummaryLength = 70
  offlineSearchMaxResults = 10
  #prism_syntax_highlighting = false
  #search = algolia

  [params.copyright]
    authors =  "Rollspelspoolen | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0)"
    from_year = 2017

  [params.taxonomy]
    # set taxonomyCloud = [] to hide taxonomy clouds
    taxonomyCloud = ["tags", "categories"]
    # If used, must have same length as taxonomyCloud
    taxonomyCloudTitle = ["Tag Cloud", "Categories"]
    # set taxonomyPageHeader = [] to hide taxonomies on the page headers
    taxonomyPageHeader = ["tags", "categories"]

  [params.ui]
    breadcrumb_disable = false
    navbar_logo = true
    navbar_translucent_over_cover_disable = false
    showLightDarkModeMenu = true
    sidebar_cache_limit = 10
    sidebar_menu_compact = true
    sidebar_menu_foldable = true
    sidebar_search_disable = false

    [params.ui.readingtime]
      enable = false

  [params.plantuml]
    enable = true
    theme = "default"
    svg_image_url = "https://www.plantuml.com/plantuml/svg/"
    svg = false
  [params.print]
    disable_toc = false
  [params.markmap]
    enable = true
  [params.drawio]
    enable = true
